/**
 * @fileoverview Provides a comprehensive set of stop words for keyword extraction.
 * This list is generated by combining a standard English stop-word list
 * with a custom-curated list of programming-specific keywords and common technical jargon.
 * This helps filter out noise when analyzing task descriptions.
 * The list is exported as a pre-built Set for optimal O(1) lookup performance.
 * To extend, add new words to the `STOP_WORDS` array.
 */

// A comprehensive list of stop words, including common English words and programming-related terms.
const STOP_WORDS: readonly string[] = [
  // Common English Stop Words (and variants)
  'a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an', 'and', 'any', 'are', 'as', 'at',
  'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by',
  'can', 'could',
  'did', 'do', 'does', 'doing', 'down', 'during',
  'each',
  'few', 'for', 'from', 'further',
  'had', 'has', 'have', 'having', 'he', 'her', 'here', 'hers', 'herself', 'him', 'himself', 'his', 'how',
  'i', 'if', 'in', 'into', 'is', 'it', 'its', 'itself',
  'just',
  'me', 'more', 'most', 'my', 'myself',
  'no', 'nor', 'not', 'now',
  'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own',
  'same', 'she', 'should', 'so', 'some', 'such',
  'than', 'that', 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', 'this', 'those', 'through', 'to', 'too',
  'under', 'until', 'up',
  'very',
  'was', 'we', 'were', 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'would',
  'you', 'your', 'yours', 'yourself', 'yourselves',

  // Common Programming/Task Keywords to Ignore
  'add', 'and', 'also', 'analyze', 'api', 'app', 'application', 'apply', 'asynchronously', 'await', 'async',
  'backend', 'based', 'bug', 'build', 'button',
  'call', 'change', 'check', 'class', 'cleanup', 'client', 'code', 'codebase', 'command', 'commit', 'component', 'config', 'configuration', 'configure', 'connect', 'console', 'const', 'context', 'continue', 'core', 'correct', 'correctly', 'create', 'css',
  'data', 'database', 'debug', 'define', 'delete', 'dependency', 'deploy', 'description', 'develop', 'developer', 'directory', 'disable', 'div', 'do', 'doc', 'docs', 'documentation', 'document', 'domain', 'done',
  'element', 'enable', 'end', 'engine', 'ensure', 'entry', 'error', 'etc', 'example', 'exception', 'execute', 'existing', 'export',
  'false', 'feature', 'field', 'file', 'files', 'final', 'finally', 'fix', 'folder', 'for', 'form', 'format', 'framework', 'from', 'frontend', 'fs', 'func', 'function',
  'general', 'generate', 'get', 'git', 'given', 'global', 'go',
  'handle', 'handler', 'hardcode', 'header', 'help', 'helper', 'html',
  'id', 'if', 'ignore', 'image', 'implement', 'implementation', 'implements', 'import', 'improve', 'in', 'index', 'init', 'initialize', 'input', 'install', 'instance', 'instead', 'interface', 'introduce', 'issue', 'item', 'items',
  'javascript', 'job', 'json', 'jsx', 'jest',
  'key', 'keyword',
  'let', 'library', 'like', 'list', 'load', 'local', 'log', 'logic',
  'main', 'make', 'manager', 'manual', 'map', 'merge', 'message', 'method', 'misc', 'miscellaneous', 'mock', 'model', 'modification', 'modify', 'module', 'modules', 'move',
  'name', 'navigate', 'need', 'new', 'node', 'null', 'number',
  'object', 'one', 'open', 'operations', 'option', 'or', 'order', 'other', 'output',
  'package', 'page', 'pane', 'panel', 'parameter', 'parse', 'parser', 'part', 'path', 'perform', 'please', 'plugin', 'polyfill', 'port', 'previous', 'private', 'process', 'project', 'prompt', 'property', 'props', 'public', 'pull', 'push', 'python',
  'query',
  'react', 'read', 'readonly', 'refactor', 'regex', 'register', 'related', 'release', 'remove', 'rename', 'render', 'replace', 'repo', 'repository', 'request', 'require', 'resolve', 'resource', 'response', 'return', 'review', 'route', 'router', 'rule', 'run',
  'save', 'schema', 'scope', 'script', 'sdk', 'section', 'security', 'select', 'send', 'server', 'service', 'set', 'setting', 'settings', 'setup', 'should', 'show', 'side', 'simple', 'source', 'specific', 'start', 'state', 'static', 'step', 'steps', 'store', 'stream', 'string', 'struct', 'structure', 'style', 'stylesheet', 'support', 'sync',
  'table', 'target', 'task', 'template', 'test', 'testing', 'tests', 'text', 'then', 'time', 'to', 'toggle', 'token', 'tool', 'true', 'try', 'tsx', 'type', 'types', 'typescript',
  'ui', 'unable', 'unit', 'unknown', 'update', 'upgrade', 'url', 'use', 'user', 'using', 'util', 'utility', 'utils',
  'validate', 'value', 'values', 'var', 'variable', 'version', 'view', 'void',
  'web', 'webpack', 'when', 'window', 'with', 'work', 'workflow', 'write',
  'xml',
  'yaml', 'yml',
];

/**
 * A pre-built set of stop words for efficient O(1) lookups.
 */
export const BASE_STOPWORDS_SET = new Set(STOP_WORDS);
