/**
 * @fileoverview Provides comprehensive word lists for keyword extraction filtering.
 * This includes a set of stop words and an allowed list of short words.
 * The stop word list is generated by combining a standard English stop-word list
 * with a custom-curated list of programming-specific keywords and common technical jargon.
 * This helps filter out noise when analyzing task descriptions.
 * The lists are exported as pre-built Sets for optimal O(1) lookup performance.
 * To extend, add new words to the `STOP_WORDS` array or the `ALLOWED_SHORT_WORDS_SET`.
 */

// A comprehensive list of stop words, including common English words and programming-related terms.
const STOP_WORDS: readonly string[] = [
  // Common English Stop Words (and variants) - only words with >3 characters
  'about', 'above', 'after', 'again', 'against',
  'because', 'been', 'before', 'being', 'below', 'between', 'both',
  'could',
  'does', 'doing', 'down', 'during',
  'each',
  'from', 'further',
  'have', 'having', 'here', 'hers', 'herself', 'himself',
  'into', 'itself',
  'just',
  'more', 'most', 'myself',
  'once', 'only', 'other', 'ours', 'ourselves', 'over',
  'same', 'should', 'some', 'such',
  'than', 'that', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', 'this', 'those', 'through',
  'under', 'until',
  'very',
  'were', 'what', 'when', 'where', 'which', 'while', 'whom', 'will', 'with', 'would',
  'your', 'yours', 'yourself', 'yourselves',

  // Common Programming/Task Keywords to Ignore - only words with >3 characters
  'also', 'analyze', 'application', 'apply', 'asynchronously', 'await', 'async',
  'backend', 'based', 'build', 'button',
  'call', 'change', 'check', 'class', 'cleanup', 'client', 'code', 'codebase', 'command', 'commit', 'component', 'config', 'configuration', 'configure', 'connect', 'console', 'const', 'context', 'continue', 'core', 'correct', 'correctly', 'create',
  'data', 'database', 'debug', 'define', 'delete', 'dependency', 'deploy', 'description', 'develop', 'developer', 'directory', 'disable', 'docs', 'documentation', 'document', 'domain', 'done',
  'element', 'enable', 'engine', 'ensure', 'entry', 'error', 'example', 'exception', 'execute', 'existing', 'export',
  'false', 'feature', 'field', 'file', 'files', 'final', 'finally', 'folder', 'form', 'format', 'framework', 'from', 'frontend', 'func', 'function',
  'general', 'generate', 'given', 'global',
  'handle', 'handler', 'hardcode', 'header', 'help', 'helper', 'html',
  'ignore', 'image', 'implement', 'implementation', 'implements', 'import', 'improve', 'index', 'init', 'initialize', 'input', 'install', 'instance', 'instead', 'interface', 'introduce', 'issue', 'item', 'items',
  'javascript', 'json', 'jest',
  'keyword',
  'library', 'like', 'list', 'load', 'local', 'logic',
  'main', 'make', 'manager', 'manual', 'merge', 'message', 'method', 'misc', 'miscellaneous', 'mock', 'model', 'modification', 'modify', 'module', 'modules', 'move',
  'name', 'navigate', 'need', 'node', 'null', 'number',
  'object', 'open', 'operations', 'option', 'order', 'other', 'output',
  'package', 'page', 'pane', 'panel', 'parameter', 'parse', 'parser', 'part', 'path', 'perform', 'please', 'plugin', 'polyfill', 'port', 'previous', 'private', 'process', 'project', 'prompt', 'property', 'props', 'public', 'pull', 'push', 'python',
  'query',
  'react', 'read', 'readonly', 'refactor', 'regex', 'register', 'related', 'release', 'remove', 'rename', 'render', 'replace', 'repo', 'repository', 'request', 'require', 'resolve', 'resource', 'response', 'return', 'review', 'route', 'router', 'rule',
  'save', 'schema', 'scope', 'script', 'section', 'security', 'select', 'send', 'server', 'service', 'setting', 'settings', 'setup', 'should', 'show', 'side', 'simple', 'source', 'specific', 'start', 'state', 'static', 'step', 'steps', 'store', 'stream', 'string', 'struct', 'structure', 'style', 'stylesheet', 'support', 'sync',
  'table', 'target', 'task', 'template', 'test', 'testing', 'tests', 'text', 'then', 'time', 'toggle', 'token', 'tool', 'true', 'type', 'types', 'typescript',
  'unable', 'unit', 'unknown', 'update', 'upgrade', 'user', 'using', 'util', 'utility', 'utils',
  'validate', 'value', 'values', 'variable', 'version', 'view', 'void',
  'webpack', 'when', 'window', 'with', 'work', 'workflow', 'write',
  'yaml',
];

/**
 * A pre-built set of stop words for efficient O(1) lookups.
 */
export const BASE_STOPWORDS_SET = new Set(STOP_WORDS);

/**
 * A pre-built set of short words (<= 3 chars) that should NOT be filtered out.
 * This is an exception list to the short-word filter rule.
 */
export const ALLOWED_SHORT_WORDS_SET = new Set<string>([
  'gui',
  'ux',
  'cli',
  'aws',
  'gcp',
  'k8s',
  'wip',
  'e2e',
]);
